### GET ALL PRODUCTS
GET http://localhost:3000/products

### GET PRODUCT BY ID
GET http://localhost:3000/products/3

### CREATE PRODUCT
POST http://localhost:3000/products/create
Content-Type: application/json

{
    "title": "Tux",
    "description": "some description",
    "price": 6900

}

### CREATE NEW USER
POST http://localhost:3000/users/auth/register
Content-Type: application/json

{
    "email": "alyzidan3@apex.com",
    "password": "admin@2020.com"
}

### Login USER
POST http://localhost:3000/users/auth/login
Content-Type: application/json

{
    "email": "alyzidan@apex.com",
    "password": "admin@2020.com"
}

### get USER
GET http://localhost:3000/users/9



### Update PRODUCT BY ID
Put http://localhost:3000/products/3
Content-Type: application/json

{
    "title": "MODIFIED",
    "description": "MODIFIED",
    "price":22
}
