### GET ALL PRODUCTS
GET http://localhost:3000/products

### GET PRODUCT BY ID
GET http://localhost:3000/products/3

### CREATE PRODUCT
POST http://localhost:3000/products/create
Content-Type: application/json

{
    "title": "lab lab",
    "description": "some description",
    "price": 2
}

### Update PRODUCT BY ID
Put http://localhost:3000/products/3
Content-Type: application/json

{
    "title": "MODIFIED",
    "description": "MODIFIED",
    "price":22
}
